### PR TITLE
Use weave:peerGroupName tag to identify peers

### LINKED ISSUE #1: Update peers.sh to detect if instance is part of a spot fleet
Spot Fleets are a very new feature in AWS that, from a cost-savings perspective, could be very beneficial when used in conjunction with ECS, especially for temporary and potentially large environments, i.e. QA and Testing.

The peers.sh script looks like it could easily be updated to failover to detecting if an instance is part of a spot fleet via http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-fleet-instances.html, which could then grab the list of peer ips since that command returns the instance ids.

I plan on beginning testing spot fleets shortly, and will update the script in a PR, if you guys don't want to try your hand at it first.

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #1

Improves #73

@bryanvaz PTAL. I have never used spot fleets, but the documentation shows they queried in the same way as normal instances, so I think this should work. I would appreciate if you could verify it though.

### CODE REVIEW

**Comment by 2opremio** [comment]
This is the only change pending the next release (https://github.com/weaveworks/integrations/pull/83) I will wait until tomorrow to see if @bryanvaz  has any comments, otherwise I will just do the customary testing and cut a release.

**Comment by 2opremio** [comment]
(CC @randywallace)

**Comment by 2opremio** [comment]
(CC @djeusette )

**Comment by 2opremio** [comment]
I have tested this successfully, merging. Release coming up soon.

**Comment by bryanvaz** [comment]
@2opremio is this in the newest AMI (ami-4e36fe2d for ap-southeast-1)? It doesn't seem to work for me.

**Comment by bryanvaz** [comment]
Here are screenshots, I have to sanatize the terraform before I can post it
**ECS:**
ecs

**EC2:**
ec2

**m3 ASG:**
m3asg

**hub ASG:**
hub

**Security Group:**
sg

**Weave Status (on m3):**

```
        Version: 1.4.5

        Service: router
       Protocol: weave 1..2
           Name: 86:bd:96:92:f3:4d(ip-172-31-23-92)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 0
    Connections: 0
          Peers: 1
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 10.32.0.0-10.47.255.255
  DefaultSubnet: 10.32.0.0/12

        Service: dns
         Domain: weave.local.
       Upstream: 172.31.0.2
            TTL: 1
        Entries: 4

        Service: proxy
        Address: unix:///var/run/weave/weave.sock
```

**Comment by 2opremio** [comment]
@bryanvaz Your AMI ID is correct. However, your tag has key `weave` and value `peerGroupName=fleetyars` but it should have key `weave:peerGroupName` (note the colon) and value `fleetyards`. 

I see that the confusion most probably comes from the documentation, sorry about that. I will clarify it further.

**Comment by 2opremio** [comment]
@bryanvaz Also, please make sure to allow `ec2:DescribeTags` actions from the instances, as explained at https://github.com/weaveworks/integrations/tree/master/aws/ecs#2-additional-amazon-ecs-api-action-permissions

**Comment by bryanvaz** [comment]
So there is definitely something strange, creating a normal weave ASG works fine. As soon as I add the key, nothing but Scope boots up, no ECS, no weave, nothing. I'm going to modify the demo weave code for tags and send it over (sanitizing terraform is just too insane).

**Comment by 2opremio** [comment]
@bryanvaz For the machines in which it doesn't work please:
1. ssh into the machine
2. Get me the output of:
    * bash -x `/etc/weave/peers.sh`
    * `docker ps`
    * `sudo initctl list`
    * `sudo grep 'scope\|init:' /var/log/messages`
    * `weave status`
    * `docker logs weave`

**Pull request merged**
