### PR TITLE
Update Weave Net, Scope and base AMIs to the latest versions

### LINKED ISSUE #132: update AMI with Weave Net 2.x
The current AMI doesn't work with Weave Net 2.x. One problem is that  https://github.com/weaveworks/integrations/blob/master/aws/ecs/packer/to-upload/run.sh invokes `weave launch-router`, which no longer exists. There are likely other breakages along similar lines.

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #132

### CODE REVIEW

**Comment by 2opremio** [comment]
@errordeveloper @pidster ping

**Comment by rade** [comment]
cc @bboreham for reviewing the net bits

**Comment by rade** [comment]
Looks like we need to do another scope release and bump the version here, because of https://github.com/weaveworks/scope/issues/2850#issuecomment-329198385.

**Comment by 2opremio** [comment]
That will require, generating new images and re-testing them (basically doing everything again), so I would rather release this and make another release later on.

**Comment by rade** [comment]
Does scope 1.6.4 work fine for you, i.e. you aren't seeing weaveworks/scope#2850?

If so then yes, let's proceed.

**Comment by 2opremio** [comment]
I didn't see that during my ECS tests.

**Pull request merged**
