### PR TITLE
missing $ for aws command execution

### PR DESCRIPTION
**Pull request by acaire**

### CODE REVIEW

**Comment by 2opremio** [comment]
@acaire Thanks. Good catch! 

I wonder how did you notice (`/usr/local/bin` is in Upstart's path which makes it work just fine in the our ECS image). 

Was it manual inspection or are you creating your our AMI?

**Comment by acaire** [comment]
Thanks for merging @2opremio 

I'm using a custom peers.sh to do auto-discovery using tags across multiple ASGs (i.e. in our case Spot and Non-Spot).  I could've sworn I experienced a failure earlier than this (because for some reason I've added a sed line in my bootcmd to add the '$') but can't reproduce it now so I probably did just discover it while debugging the script.

**Comment by 2opremio** [comment]
Oh, cool! Would you mind sending us an email at help@weave.works describing your use case and telling us what would you like us to improve (related to ECS and about Weave in general)?

**Comment by 2opremio** [comment]
Also, regarding your peer discovery requirements. Would mind elaborating/sharing what specific changes you had to make?

Would implementing https://github.com/weaveworks/integrations/issues/1 help you?

**Pull request merged**
