### PR TITLE
Expand documentation

### LINKED ISSUE #25: Improve documentation
The ECS AMI README simply includes the AMI Ids and how to create your own AMI. We should include things like:

* How peer instance discovery works
* What Scope works (app+probe per node)
* How do you provide tokens for Scope-aaS probes.
* What tcp/udp ports should be open between instances.
* What extra instance policy restrictions are needed.

Most of this is already explained in the ECS guide but should also (or only) be present in the documentation.

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #25 

@abuehrle @kpoplin  PTAL

### CODE REVIEW

**Comment by 2opremio** [comment]
I used the terms `hosted-mode` and `standalone-mode` to refer to Scope running in http://scop.weave.works and locally on ECS. I welcome better terms.

**Comment by abuehrle** [comment]
@2opremio I'll have a look tomorrow.  I believe the rule is: `Weave Scope` is the product, and then you can refer to how it's accessed in lower case, so as long as those terms are lowercase then they should be fine.  But I'll try them out and see how they flow in the doc.

**Comment by 2opremio** [comment]
Sure, thanks!

**Comment by abuehrle** [comment]
@2opremio here's some edits for you. Please make sure I haven't changed the meaning of anything in here.

**Comment by abuehrle** [comment]
Ok sure I will change those things.

**Comment by 2opremio** [comment]
Comments-aside LGTM. Thanks @abuehrle !

**Comment by 2opremio** [comment]
Ops, I just realized that the [Scope README](https://github.com/weaveworks/scope) uses different nomenclature for what I have called `hosted` and `standalone`. I will rename them to *Service mode* and *Multi-host* mode to be consistent.

**Comment by abuehrle** [comment]
Standalone and hosted sounds more standard.  I would change the readme.

**Comment by 2opremio** [comment]
@abuehrle I think you are right, will create a PR for scope and see how the team reacts.

**Comment by abuehrle** [comment]
You should include Katie and Mathew on that. That is really a marketing responsibility on how the products should be referencedm not developers.  Although, they may have an opinion, they are not the ones who have to sell the product :)

**Comment by 2opremio** [comment]
True

**Comment by kpoplin** [comment]
I just added this suggestion to https://github.com/weaveworks/scope/pull/594 -
here's how I referenced the product and 2 different modes in which it can
be used:

“Using Weave Scope in Hosted Mode” and “Using Weave Scope in Standalone
Mode”



On 26 October 2015 at 12:27, Alfonso Acosta <notifications@github.com>
wrote:

> True
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weaveworks/integrations/pull/27#issuecomment-151257479>
> .
>



-- 
Katie Poplin
VP Marketing
Weave <http://weave.works/>
Mobile: +1.415.343.5671

**Comment by abuehrle** [comment]
Thanks Katie, I had those headings already.  This is something I will add to the Style Guide, though, ie. verbs in heading.

**Comment by 2opremio** [comment]
Style Guide? I should read that!

**Comment by 2opremio** [comment]
I rebased, squashed everything and did some width reformatting.

**Pull request merged**
