### PR TITLE
CloudFormation changes to move away from vendored AMIs

### PR DESCRIPTION
**Pull request by errordeveloper**
Please don't merge yet, let's discuss what's going on. It also needs some more testing around any potential edge-cases.

### CODE REVIEW

**Comment by errordeveloper** [comment]
Not sure if you will notice right away, but this doesn't even run any shell commands directly, which I'm quite happy about.

**Comment by errordeveloper** [comment]
@2opremio I'm fairly happy with this, the only thing I'd like to discuss is the `/etc/init/ecs.override` file. What I think _may_ happen is that this file could get written to disk after the original `ecs` service gets started. I can see how the chances may be very minimal, but it's still a race condition unless we can prove otherwise. Previously, we had no issue with such a race condition due to an effective reboot.

**Comment by 2opremio** [comment]
@errordeveloper If:
* Upstart reloads the file as soon as it's written (which we should confirm)
* CloudFormation:Init is run as part of the machine's cloud-init (please confirm this too)

 I don't see how can there be a race condition because cloud-init is run as part of the systemv init and ecs is started [after that](https://github.com/aws/amazon-ecs-init/blob/8bc7f0062cba155ce985c7afcccf28b420a1d17e/packaging/amazon-linux-ami/ecs.conf#L17):

```
start on stopped rc RUNLEVEL=[345]
```

If I recall properly, the rc signal is only emitted as part as the legacy systemv init scripts, once they are done executing.

**Comment by errordeveloper** [comment]
> `CloudFormation::Init` is ran as part of the machine's cloud-init (please confirm this too)

Yes, it's [triggered via `UserData`](https://github.com/weaveworks/integrations/blob/e9320e1b66e4ac27ff1a49fc2d21610a10a437ff/aws/ecs/cloudformation.json#L520-L540).

**Comment by errordeveloper** [comment]
> Upstart reloads the file as soon as it's written (which we should confirm)

Upstart [uses `inotify(7)`](http://manpages.ubuntu.com/manpages/precise/man5/init.5.html), is is a good enough answer?

**Pull request merged**
